train:
  iterations: &max_iter 4000
  log_image_interval: 200
  save_ckpt_interval: 1000
  max_images: 2
  vis_grad: true

synthesizer:  # the model 'f' to generate new image when ensuring fidelity
  target: synthesizer.stylegan_synthesizer.StyleganMapperSynthesizer
  params:
    generator:
      target: models.stylegan2.model.StyleGANv2Generator
      params:
        size: &resolution 1024
        style_dim: &style_dim 512
    generator_ckpt: ./pretrain/stylegan2-ffhq-config-f.pt

    data:
      bs_per_gpu: 2
      num_workers: 2
      target: dataset.LatentsDataset
      params:
        path: ./data/train_celeba_w+_codes.pt

    mapper:
      target: models.mapper.latent_mappers.LevelsMapper
      params:
        coarse: False
        medium: True
        fine: True
    work_space: &work_space w+
    trunction: 1
    latent_weight: 0.1
    resolution: *resolution

guidance_loss:
  target: loss.guidance_loss.sd_loss.SDLoss
  params:
    loss_weight: 1.0
    text: white hair
    t_policy: fixed_800
    clip_grad: True
    clip_grad_topk: 1024
    noise_type: random
    skip: True
    max_iter: *max_iter

regularization_losses:
  - target: loss.regularization_loss.l2_loss.L2Loss
    params:
      space: *work_space
      loss_weight: 10.0
  - target: loss.regularization_loss.id_loss.IDLoss
    params:
      loss_weight: 1.0
      path: ./pretrain/model_ir_se50.pth

optimizer:
  params:
    lr: 0.005
    weight_decay: 0.002

search:
  metrics_type: entropy
  min_step: 100
  max_step: 900
  search_step: 50
  vis_step_interval: 50
  select_by: min
  num_sample: 200

inference:
  ckpt: ./pretrain/white_hair.pt
  data:
    bs_per_gpu: 1
    num_workers: 2
    target: dataset.LatentsDataset
    params:
      path: ./data/test_faces.pt
